services:
  python:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: python
    tty: true
    command: /bin/sh -c "while :; do sleep 10; done"
    volumes:
      - ./:/src
